### PR TITLE
Show all recipes from individual recipe view

### LINKED ISSUE #40: All recipes button not working
When the user clicks on an individual recipe, then clicks on the All Recipes button it does not take them back to all recipes. @pthan1

### PR DESCRIPTION
**Pull request by pthan1**
## Description

Please include a summary of the change and/or functionality implementation:
Shows all recipes when button is clicked from an individual recipe

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] open index.html

## Checklist:

- [x] I have performed a self-review of my own code
- [x] No console error messages

## Additional info
Please include any other relevant information here:
closes #40

### CODE REVIEW

**Review by EricSergeant — APPROVED** [review]
Excellent, clean update to fix a bug.

**Review by Logandv3 — APPROVED** [review]
Oh yeah!

File: src/scripts.js [hunk 1]
```diff
@@ -179,7 +180,6 @@ function showIndividualRecipe(event) {
 };
 
 function hideIndividualRecipe() {
-  event.preventDefault();
```
Comment (elisebeall) [inline src/scripts.js:182]: Great job with deleting this one line.
